apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-secret
spec:
  containers:
    - image: nginx:1.14.2
      name: container-0
      volumeMounts:
        - name: vol-secret
          mountPath: "/tmp"
  imagePullSecrets:
    - name: default-secret
  volumes:
    - name: vol-secret
      secret:
        secretName: mysecret
