apiVersion: v1
kind: Pod
metadata:
  name: pod-private-regcred-secret
spec:
  containers:
    - name: private-reg-container
      image: venture007-docker.pkg.coding.net/cka/istio/examples-bookinfo-details-v1:1.18.2
  imagePullSecrets:
    - name: my-secret