apiVersion: v1
kind: Pod
metadata:
  name: pod-command-configmap
spec:
  containers:
    - name: test-container
      image: nginx:1.14.2
      command: [ "/bin/sh", "-c"]
      args: ["echo $(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)"]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never