apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # must be same as task-pv-volume (binding volumeName-PV)
  resources:
    requests:
      storage: 3Gi
  volumeName: task-pv-volume

---------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-pvc-cka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: blue-stc-cka
  volumeName: blue-pv-cka
