apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
    - name: myapp-container
      image: nginx:1.14.2
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
    - name: init-container-1
      image: nginx:1.14.2
      command: ['sh', '-c', 'echo init-container-1 start && sleep 30']
    - name: init-container-2
      image: nginx:1.14.2
      command: ['sh', '-c', "echo init-container-2 start  && sleep 30"]